### ISSUE TITLE
[Bug] Some Keyboard setting keys are not works

### ISSUE THREAD

**Issue by vexc-how-design** [joric/qmk_firmware#10]
Hi Joric,

Hardware: nrfmicro 1.3
Software: your new firmware with Jorne_ble

I found out some custom keys are not works, such as DELBNDS, BLE_EN, BLE_DIS, USB_EN and USB_DIS.

Maybe is my setup problem.
Can you please give me some suggestion? Thanks!

**Comment by joric** [comment]
I don't know. It should, check keymap file. Latest firmware is very experimental, try ZMK instead, it has official nRFMicro and Jorne support now,

**Comment by lulzkdm** [comment]
good!
