### ISSUE TITLE
Is Jorne compatible with QMK Online Configurator?

### ISSUE THREAD

**Issue by MickeyLangelo** [joric/qmk_firmware#11]
Is it possible to use QMK Online Configurator to customize Jorne's layouts? There's no Jorne in the list of compatible keyboards but may be I can choose Jian instead? If so, which one - there are Rev1, Rev2 and nsrev2 versions for Jian in QMK Configurator. 
![Screenshot 2021-06-27 at 21 45 32](https://user-images.githubusercontent.com/86039363/123555892-21122880-d791-11eb-9770-4b6bea2300f4.png)

**Comment by joric** [comment]
Nope. Don't have time. Jian is not matrix-compatible. The closest thing is crkbd =(
