### ISSUE TITLE
[Bug] cannot close OLED_ENABLE

### ISSUE THREAD

**Issue by billionfish** [joric/qmk_firmware#15]
I set all OLED_ENABLE= no,but still has compile error when make slave, the master has no error.
![image](https://user-images.githubusercontent.com/26395551/156729464-52010f4e-e672-4d96-aae7-3be4ccfd6db5.png)

![image](https://user-images.githubusercontent.com/26395551/156729629-c581a66b-ae5f-455d-94b7-1b842e071eca.png)

**Comment by joric** [comment]
Not sure. QMK is really abandoned for now in favor of ZMK, so you're on your own.

**Comment by billionfish** [comment]
thank you for your reply
