### ISSUE TITLE
build failure on nrf5x branch

### ISSUE THREAD

**Issue by chris-ryu** [joric/qmk_firmware#16]
I cannot compile on nrf5x branch.

I'm building make mitosis_ble/master

OS: macOS 12.3.1
CPU: M1 Max

Compiling: tmk_core/protocol/nrf/matrix.c                                                          In file included from tmk_core/protocol/nrf/matrix.c:32:
tmk_core/protocol/nrf/matrix.c: In function 'matrix_init':
/Users/chrisryu/nrf_sdk/nRF5SDK1230/nRF5_SDK_12.3.0_d7731ad/components/drivers_nrf/hal/nrf_gpio.h:514:17: error: array subscript 4294967295 is above array bounds of 'volatile uint32_t[32]' {aka 'volatile long unsigned int[32]'} [-Werror=array-bounds]
  514 |     reg->PIN_CNF[pin_number] = ((uint32_t)dir << GPIO_PIN_CNF_DIR_Pos)
      |     ~~~~~~~~~~~~^~~~~~~~~~~~
In file included from /Users/chrisryu/nrf_sdk/nRF5SDK1230/nRF5_SDK_12.3.0_d7731ad/components/device/nrf.h:62,
                 from /Users/chrisryu/nrf_sdk/nRF5SDK1230/nRF5_SDK_12.3.0_d7731ad/components/drivers_nrf/delay/nrf_delay.h:43,
                 from tmk_core/common/wait.h:19,
                 from tmk_core/protocol/nrf/matrix.c:26:
/Users/chrisryu/nrf_sdk/nRF5SDK1230/nRF5_SDK_12.3.0_d7731ad/components/device/nrf51.h:1087:18: note: while referencing 'PIN_CNF'
 1087 |   __IO uint32_t  PIN_CNF[32];                       /*!< Configuration of GPIO pins.                                           */
      |                  ^~~~~~~
cc1: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [.build/obj_mitosis_ble_master_default/protocol/nrf/matrix.o] Error 1
make: *** [mitosis_ble/master] Error 1
Make finished with errors

**Comment by joric** [comment]
Can't really help here, don't have a mac!

**Comment by chris-ryu** [comment]
Thank you.

I can reproduce the exact same problem on ubuntu 20.04.

❯ make mitosis_ble/master
Making mitosis_ble/master with keymap default

"PLATFORM NRF5"
Compiling: tmk_core/protocol/nrf/sdk12/ble_advertising.c                                            [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/log/src/nrf_log_backend_serial.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/log/src/nrf_log_frontend.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/button/app_button.c     [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/util/app_error.c        [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/util/app_error_weak.c   [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/scheduler/app_scheduler.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/timer/app_timer.c       [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/timer/app_timer_appsh.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/util/app_util_platform.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/crc16/crc16.c           [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/fds/fds.c               [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/fstorage/fstorage.c     [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/hardfault/hardfault_implementation.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/util/nrf_assert.c       [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/util/sdk_errors.c       [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/libraries/util/sdk_mapped_flags.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/drivers_nrf/clock/nrf_drv_clock.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/drivers_nrf/common/nrf_drv_common.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/drivers_nrf/gpiote/nrf_drv_gpiote.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/drivers_nrf/uart/nrf_drv_uart.c   [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/common/ble_advdata.c          [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/common/ble_conn_params.c      [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/common/ble_conn_state.c       [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/common/ble_srv_common.c       [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/gatt_cache_manager.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/gatts_cache_manager.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/id_manager.c     [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/peer_data.c      [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/peer_data_storage.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/peer_database.c  [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/peer_id.c        [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/peer_manager.c   [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/pm_buffer.c      [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/pm_mutex.c       [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/security_dispatcher.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/peer_manager/security_manager.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/ble_db_discovery/ble_db_discovery.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/ble_services/ble_bas/ble_bas.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/ble_services/ble_dis/ble_dis.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/ble_services/ble_hids/ble_hids.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/ble_services/ble_nus_c/ble_nus_c.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/ble/ble_services/ble_nus/ble_nus.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/softdevice/common/softdevice_handler/softdevice_handler.c [OK]
Compiling: /home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/softdevice/common/softdevice_handler/softdevice_handler_appsh.c [OK]
arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/mitosis_ble/mitosis_ble.c                                                      [OK]
Compiling: keyboards/mitosis_ble/master/master.c                                                   /tmp/ccQCbAje.s: Assembler messages:
/tmp/ccQCbAje.s: Warning: unable to rebuffer file: keyboards/mitosis_ble/master/master.c

 [OK]
Compiling: keyboards/mitosis_ble/keymaps/default/keymap.c                                           [OK]
Compiling: quantum/quantum.c                                                                        [OK]
Compiling: quantum/keymap_common.c                                                                  [OK]
Compiling: quantum/keycode_config.c                                                                 [OK]
Compiling: quantum/process_keycode/process_leader.c                                                 [OK]
Compiling: tmk_core/common/host.c                                                                   [OK]
Compiling: tmk_core/common/keyboard.c                                                               [OK]
Compiling: tmk_core/common/action.c                                                                 [OK]
Compiling: tmk_core/common/action_tapping.c                                                         [OK]
Compiling: tmk_core/common/action_macro.c                                                           [OK]
Compiling: tmk_core/common/action_layer.c                                                           [OK]
Compiling: tmk_core/common/action_util.c                                                            [OK]
Compiling: tmk_core/common/print.c                                                                  [OK]
Compiling: tmk_core/common/debug.c                                                                  [OK]
Compiling: tmk_core/common/util.c                                                                   [OK]
Compiling: tmk_core/common/eeconfig.c                                                               [OK]
Compiling: tmk_core/common/report.c                                                                 [OK]
Compiling: tmk_core/common/nrf/suspend.c                                                            [OK]
Compiling: tmk_core/common/nrf/timer.c                                                              [OK]
Compiling: tmk_core/common/nrf/bootloader.c                                                         [OK]
Compiling: tmk_core/common/nrf/printf.c                                                             [OK]
Compiling: tmk_core/common/nrf/eeprom.c                                                             [OK]
Compiling: tmk_core/common/magic.c                                                                  [OK]
Compiling: tmk_core/protocol/nrf/matrix.c                                                          In file included from tmk_core/protocol/nrf/matrix.c:32:
tmk_core/protocol/nrf/matrix.c: In function 'matrix_init':
/home/narzis/NRFSDK/nRF5_SDK_12.3.0_d7731ad/components/drivers_nrf/hal/nrf_gpio.h:514:17: error: array subscript 4294967295 is above array bounds of 'volatile uint32_t[32]' {aka 'volatile long unsigned int[32]'} [-Werror=array-bounds]
  514 |     reg->PIN_CNF[pin_number] = ((uint32_t)dir << GPIO_PIN_CNF_DIR_Pos)
      |     ~~~~~~~~~~~~^~~~~~~~~~~~
cc1: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [tmk_core/rules.mk:362: .build/obj_mitosis_ble_master_default/protocol/nrf/matrix.o] Error 1
Make finished with errors
make: *** [Makefile:544: mitosis_ble/master] Error 1

**Comment by joric** [comment]
Wiki says You will need SDK13, not SDK15 for this branch. https://github.com/joric/qmk/wiki/nrf5x
It's also totally unfinished so there's no much sense in building it and asking me for help. I mean it won't work (possibly ever) if you even managed to build it somehow,
