### ISSUE TITLE
Noob Flashing Issue

### ISSUE THREAD

**Issue by glow12121** [joric/qmk_firmware#17]
Hi,

I am a total noob and trying to re-flash my Jorne because it seems the left half is having some issues.

As I try to `avrdude -p atmega32u4 -P COM11 -c avr109  -e -U flash:w:crkbd_rev1_jorne.hex`, as described [here](https://github.com/joric/qmk/wiki/jorne#uploading-firmware), it says I first need to point at the device: `avrdude: ser_open(): can't open device "COM11": No such file or directory`.

I am on Linux. How should I detect my Jorne in this situation?

Thanks.

**Comment by joric** [comment]
It's a regular pro-micro based QMK keyboard, try QMK flashing tutorials. Maybe this will help https://github.com/samhocevar-forks/qmk-firmware/blob/master/docs/newbs_flashing.md
