### ISSUE TITLE
how to build a non-split keyboard with this firmware?

### ISSUE THREAD

**Issue by xiaoquanaa** [joric/qmk_firmware#2]
Hey， big brother, i am so glad to see your project of the nrf52840 keyboard . i was thinking about building a key 87 keyboard with nrf52840 . but i saw that all you project is about split keyboard , if i want to build a normal keyboard(non-split) with just one nrf52 module ， how should i modify the firmware from yours , could i just compile the master's firmware?
         and still another question , there are few things about the sleeping mode and battery life are mentioned in your wiki , i just want to know the keyboard will go to sleep without typing in how many seconds.
     can you give me some advices in your spare  time ?

**Comment by joric** [comment]
I think sekigon has a lot of non-split examples, e.g. https://github.com/sekigon-gonnoc/qmk_firmware/tree/nrf52/keyboards/angel64_ble

Regarding sleep mode I couldn't really find anything besides BLE_ADV_EVT_IDLE event that puts the system to sleep. I guess it's about 3 minutes, but not sure how to modify it.
