### ISSUE TITLE
Call matrix_init_quantum from matrix_init()

### ISSUE THREAD

**Issue by okke-formsma** [joric/qmk_firmware#6]
in https://github.com/joric/qmk/blob/nrf52-jorne/tmk_core/protocol/nrf/matrix.c#L184 matrix_init_user() is called instead of the normal call chain of matrix_init_quantum -> matrix_init_kb -> matrix_init_user.

This forces keyboards to use the matrix_init_user() method instead of matrix_init_kb, and robs users from configuring their own init funcs.

I'll make a pull request for this.

**Comment by joric** [comment]
merged
