### ISSUE TITLE
How to rewrite the init_kb function if i set DIODE_DIRECTION == ROW2COL?

### ISSUE THREAD

**Issue by jiaxin96** [joric/qmk_firmware#8]
https://github.com/joric/qmk/blob/608febee5537490c2c1c1f95837aa95b6a60ce93/keyboards/jorne_ble/master/master.c#L46
void matrix_init_kb() {
  nrfmicro_init();

  select_row(3);
  wait_us(50);
  matrix_row_t row = read_cols();
  unselect_rows();
  if (row == 0b111000) {
    delete_bonds();
  } else if (row == 0b10) {
    bootloader_flag = true;
  }

**Comment by joric** [comment]
This is the hardcoded reset code that's not used, you just need `#define DIODE_DIRECTION ROW2COL` in config h.
